### ISSUE TITLE
display a notice if current website is not a moodle site

### ISSUE THREAD

**Issue by YukinoHayakawa** [SEIAROTg/Moodown#3]
instead of displaying the default menu, maybe showing a notice saying that the extension cannot be used on current site would make the interface more consistency thus reduces confusion.

**Comment by SEIAROTg** [comment]
In early version of Google Chrome the extension icon is supposed to be in the address bar and invisible when not applicable to current webpage. However, Chrome later move all extension icons outside the address bar in some version [\[See this\]](https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-extensions/upcoming/chromium-extensions/7As9MKhav5E/dNiZDoSCCQAJ). I was hoping this change could be reversed but now I might need to make a change as you said.
