### ISSUE TITLE
Moodown affecting the dragging bottoms' functioning when "customising this page"-ing moodle.Nottingham: My home

### ISSUE THREAD

**Issue by numerousC** [SEIAROTg/Moodown#7]
The module bars in the Module Overview block cannot be dragged (and hence reordered) when Moodown is enabled. Also the icon of the dragging bottoms which indicates the place where the mouse should be dragging have also been changed from the cross to some grey rectangular shape when Moodown is enabled.

**Comment by SEIAROTg** [comment]
Not sure if this problem is caused by Moodown. Anyway, now that the acceleration feature has been moved, Moodown should not interfere with the page content any more.
