### ISSUE TITLE
Moodown preventing loading of TurnItIn file uploading block

### ISSUE THREAD

**Issue by numerousC** [SEIAROTg/Moodown#8]
**Problem:** 
The TurnItIn submitting block seemed to be loading for ever with a "loading" pic hanging where the block should've been (or maybe it's just not gonna be loaded, I guess) when Moodown is enabled. 

**Expected behaviour:** 
The block will be loaded and hence the file upload can be operated within the block, whether via dragging or whatever. It seemed not to be an issue before the accelerator branch is merged into master.

**Comment by numerousC** [comment]
It looks like this when Moodown is enabled:

![image](https://cloud.githubusercontent.com/assets/24740982/23019966/bb4f8f9a-f47f-11e6-84df-1e2378b20794.png)

As I said it could just be a slow loading, or it was probably not loading anyway. Either way, the icon on the tab (on Chrome) says that the page had stopped loading (no loading wheel).

**Comment by SEIAROTg** [comment]
The trouble making acceleration feature has been removed and the problem should not exist any more.
